ASM nasm


SRC_DIR src
BUILD_DIR build

$(BUILD_DIR)/vlaicu_os.img: $(BUILD_DIR)/vlaicu.bin
	cp $(BUILD_DIR)/vlaicu.bin $(BUILD_DIR)/vlaicu_os.img
	truncate -s 1440k $(BUILD_DIR)/vlaicu_os.img

$(BUILD_DIR)/vlaicu.bin: $(SRC_DIR)/main.asm
	$(ASM) $(SRC_DIR)/main.asm -f bin -o $(BUILD_DIR)/vlaicu.bin