$(function(){
    $('.setteng_pcinfo').click(function(){
        $('.setteng_pcinfo_notlist').removeClass('hidden');
        $('.setteng_personalization_notlist').addClass('hidden');
        $('.setteng_recovery_notlist').addClass('hidden')
    });
    $('.setteng_personalization').click(function(){
        $('.setteng_pcinfo_notlist').addClass('hidden');
        $('.setteng_personalization_notlist').removeClass('hidden');
        $('.setteng_recovery_notlist').addClass('hidden')
    });
    $('.setteng_recovery').click(function(){
        $('.setteng_pcinfo_notlist').addClass('hidden');
        $('.setteng_personalization_notlist').addClass('hidden');
        $('.setteng_recovery_notlist').removeClass('hidden')
    });
});