var s = new Array();

// OS X MERCURY
// CODE NAME ASTEROID
// (c) 2007 Marcus Strehlow

// MOONLIGHT SEARCH INDEX
// THIS FOLLOWS A CERTAIN STRUCTURE, AND HAS BEEN MODIFIED TO HAVE THE ALL-LOVED SPOTLIGHT LOOK!
// TOUCH THIS, AND I TOUCH YOU

// s[NUM] = "TITLE^URL^CONTENT^RANK"

// * NUM has to start at 0, then counting up
// * URL has to be the link for the application to open
// * Need to experiment around with RANK

// ----------

// * KIND 	 = What is it? Document, System Preference, Music, Picture, Folder...
// * CONTENT = Name of the file 
// * URL	 = Which application should be opened (linked with CONTENT!!)
// * ICON	 = Small icon representing the kind of file
// * ^^		 = Seperator between URL and CONTENT - do not change or modify

// ----------

// ----
// MOONLIGHT INDEX STARTS
// ----

// --- Music files begin

s[0] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Music</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Ignition</a></td></tr></table>";

s[1] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Music</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>TranceMission</a></td></tr></table>";

s[2] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Music</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>I take you higher</a></td></tr></table>";

s[3] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Music</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Cubic</a></td></tr></table>";

s[4] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Music</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>I am going tonight</a></td></tr></table>";

s[5] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Music</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Rhapsody in E</a></td></tr></table>";

s[6] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Music</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Seven Years (94/01)</a></td></tr></table>";

s[7] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Music</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Zebras Crossing The Street</a></td></tr></table>";

s[8] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Music</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Liquid Flute</a></td></tr></table>";

// --- Music files end.

// --- ---------------------------- ---

// --- Photo files begin. It shows previews! Yay!

s[9] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Images</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiPhotoRoll01('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_images.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>All Over Ireland</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"thumbs/all_over_ireland_01.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/all_over_ireland_02.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/all_over_ireland_03.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[10] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Images</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiPhotoRoll02('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_images.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>City Centre</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"thumbs/citycentre_01.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/citycentre_02.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/citycentre_03.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[11] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Images</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiPhotoRoll03('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_images.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Ennis / Galway</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"thumbs/ennisgalway_01.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/ennisgalway_02.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/ennisgalway_03.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[12] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Images</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiPhotoRoll04('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_images.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Howth 19 / 06 / 04</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"thumbs/howth_01.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/howth_02.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/howth_03.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[13] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Images</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiPhotoRoll05('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_images.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>The Blanchardstown Centre</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"thumbs/blanch_01.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/blanch_02.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/blanch_03.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[14] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Images</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiPhotoRoll06('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_images.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Wexford 03 / 06 / 04</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"thumbs/wexford_01.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/wexford_02.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/wexford_03.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[15] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Images</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiPhotoRoll07('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_images.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Bettystown Avenue</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"thumbs/ba_01.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/ba_02.jpg\" border=0 style=\"border:1px solid black;\">&nbsp;<img src=\"thumbs/ba_03.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

// --- Photo files end.

// --- ---------------------------- ---

// --- Time Machine contents begin.

s[16] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2007 - SE51.net</a></td></tr></table>";

s[17] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2006 - First edition of SE51</a></td></tr></table>";

s[18] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2005 - 24 / Shadow Of Memories</a></td></tr></table>";

s[19] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2005 - Sirius Bytes</a></td></tr></table>";

s[20] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2004 - last os</a></td></tr></table>";

s[21] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2004 - Online Total</a></td></tr></table>";

s[22] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2003 - Generation OS</a></td></tr></table>";

s[23] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2003 - Sk8er Boi's Corner</a></td></tr></table>";

s[24] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2002 - Giga IE</a></td></tr></table>";

s[25] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2002 - USS Unity .net</a></td></tr></table>";

s[26] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Time Machine</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>2001 - Annika Ljungberg .info</a></td></tr></table>";

// --- Time Machine ends.

// --- ---------------------------- ---

// --- Finder contents begin.

s[27] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Hard Drive</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderMercuryHD('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_hd.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Mercury HD</a></td></tr></table>";

s[28] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderNetwork('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_network.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Network</a></td></tr></table>";

s[29] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderHome('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_home.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Home</a></td></tr></table>";

s[30] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderApplications('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_applications.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Applications</a></td></tr></table>";

s[31] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderDesktop('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_desktop.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Desktop</a></td></tr></table>";

s[32] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderDocuments('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_documents.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Documents</a></td></tr></table>";

s[33] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderMusic('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Music</a></td></tr></table>";

s[34] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderPictures('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_pictures.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Pictures</a></td></tr></table>";

// --- Finder files end.

// --- ---------------------------- ---

// --- Applications listings begin.

s[35] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Application</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:showTimeMachine()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_timemachine.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Time Machine</a></td></tr></table>";

s[36] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Application</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:dashboard()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_widget.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Dashboard</a></td></tr></table>";

s[37] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Application</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariFromDock('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/app_safari.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Safari</a></td></tr></table>";

s[38] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Application</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openMail('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/app_mail.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Mail</a></td></tr></table>";

s[39] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Application</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiTunes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_music.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>iTunes</a></td></tr></table>";

s[40] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Application</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiChat('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/app_ichat.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>iChat</a></td></tr></table>";

s[41] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Application</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiWeb('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/app_iweb.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>iWeb</a></td></tr></table>";

s[42] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Application</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openiPhoto('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_images.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>iPhoto</a></td></tr></table>";

s[43] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Application</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSystemPreferences('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/app_sysprefs.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>System Preferences</a></td></tr></table>";

// --- Applications end.

// --- ---------------------------- ---

// --- Adding Dashboard Widget index.

s[44] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Widget</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:dashboard()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_widget.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>PlayStation Portable</a></td></tr></table>";

s[45] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Widget</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:dashboard()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_widget.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Wii</a></td></tr></table>";

s[46] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Widget</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:dashboard()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_widget.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>V600i</a></td></tr></table>";

s[47] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Widget</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:dashboard()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_widget.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>iPod</a></td></tr></table>";

s[48] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Widget</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:dashboard()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_widget.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>PlayStation 2</a></td></tr></table>";

s[49] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Widget</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:dashboard()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_widget.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Stargate</a></td></tr></table>";

s[50] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Widget</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:dashboard()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_widget.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>iMac G5</a></td></tr></table>";

s[51] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Widget</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:dashboard()\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_widget.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>MacBook</a></td></tr></table>";

// --- Widgets end.

// --- ---------------------------- ---

// --- Remaining items. These appear below the apparent top results.



// --- Library Folder

s[52] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderLibrary('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_folder.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Library</a></td></tr></table>";

// --- Desktop Pictures Folder

s[53] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderDesktopPictures('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_folder.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Desktop Pictures</a></td></tr></table>";

// --- 8 Desktop pictures

s[54] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Desktop Wallpaper</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openPreviewDeskPic1('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_desktop.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Aqua Blue</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"../../../../../Library/DesktopWallpaper/1024x768/thumb/AquaBlue.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[55] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Desktop Wallpaper</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openPreviewDeskPic2('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_desktop.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Aqua Graphite</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"../../../../../Library/DesktopWallpaper/1024x768/thumb/AquaGraphite.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[56] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Desktop Wallpaper</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openPreviewDeskPic3('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_desktop.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Clown Fish</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"../../../../../Library/DesktopWallpaper/1024x768/thumb/ClownFish.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[57] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Desktop Wallpaper</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openPreviewDeskPic4('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_desktop.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Evening Reflections</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"../../../../../Library/DesktopWallpaper/1024x768/thumb/EveningReflections.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[58] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Desktop Wallpaper</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openPreviewDeskPic5('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_desktop.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Faux Fur</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"../../../../../Library/DesktopWallpaper/1024x768/thumb/FauxFur.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[59] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Desktop Wallpaper</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openPreviewDeskPic6('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_desktop.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Flowing Rock</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"../../../../../Library/DesktopWallpaper/1024x768/thumb/FlowingRock.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[60] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Desktop Wallpaper</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openPreviewDeskPic7('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_desktop.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Gentle Rapids</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"../../../../../Library/DesktopWallpaper/1024x768/thumb/GentleRapids.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

s[61] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Desktop Wallpaper</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openPreviewDeskPic8('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_finder_desktop.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Jaguar Aqua Blue</a></td></tr><tr height=90><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0></td><td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=top align=left bgcolor=#dfdfdf><img src=../Resources/transparent.gif height=3 border=0><br><img src=\"../../../../../Library/DesktopWallpaper/1024x768/thumb/JaguarAquaBlue.jpg\" border=0 style=\"border:1px solid black;\"><br><br></td></tr></table>";

// --- CV.

s[62] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Document</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openCurriculumVitae('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_pdf.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Curriculum Vitae</a></td></tr></table>";

// --- Release Notes.

s[63] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Document</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openReleaseNotes('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_x.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>OS X Mercury Release Notes</a></td></tr></table>";

// --- Bookmarks and Network links.

s[64] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark01('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Apple Inc.</a></td></tr></table>";

s[65] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark02('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Apple - Mac OS X</a></td></tr></table>";

s[66] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark03('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Apple - Leopard</a></td></tr></table>";

s[67] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark04('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Google News</a></td></tr></table>";

s[68] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark05('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>The Lonely Horseman</a></td></tr></table>";

s[69] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark06('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Kubuntu</a></td></tr></table>";

s[70] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark07('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Stuff On My Cat</a></td></tr></table>";

s[71] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark08('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>1802.eu</a></td></tr></table>";

s[72] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark09('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Wired News</a></td></tr></table>";

s[73] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark10('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Blender 3D</a></td></tr></table>";

s[74] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark11('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>WINE</a></td></tr></table>";

s[75] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark12('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>YouTube</a></td></tr></table>";

s[76] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Network</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSafariBookmark13('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_bookmark.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>last fm</a></td></tr></table>";

// --- Preference Panes!

s[77] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Preference Pane</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSystemPreferences('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_prefpane.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Wallpaper</a></td></tr></table>";

s[78] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Preference Pane</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSystemPreferences('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_prefpane.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Display Resolution</a></td></tr></table>";

s[79] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Preference Pane</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openSystemPreferences('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_prefpane.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Software Update</a></td></tr></table>";

// --- Preference Panes end.

// --- ---------------------------- ---

// --- Unity files. Downloadable directly.

s[80] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Archive</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"http://sandbox.redrocksdatacenter.com/marcus/mercury/Public/Unity.zip\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_zip.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Unity and Bridge.zip</a></td></tr></table>";

s[81] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Archive</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"http://sandbox.redrocksdatacenter.com/marcus/mercury/Public/Unity-Warp-Test.zip\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_zip.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Warp Drive Test.zip</a></td></tr></table>";

// --- Unity files end.

// --- ---------------------------- ---

// --- Reason files. Downloadable directly.

s[82] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Archive</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"http://sandbox.redrocksdatacenter.com/marcus/mercury/Public/ReasonMusic.zip\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_zip.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Reason Music.zip</a></td></tr></table>";

s[83] = "<table width=100% border=0 cellspacing=0 cellpadding=0 align=center><tr height=30><td bgcolor=#f1f1f1 valign=middle align=right width=150><img src=../Resources/transparent.gif height=3 border=0><br><font face='Lucida Grande, Tahoma' size=1 color=#666666>Folder</td></font>^^<td width=15 bgcolor=#f1f1f1></td><td width=10 bgcolor=#dfdfdf></td><td width=* valign=middle align=left bgcolor=#dfdfdf onmouseover=\"this.bgColor='#0064e6'\" onmouseout=\"this.bgColor='#dfdfdf'\"><a href=\"javascript:Application.openFinderDesktopReason('mac_os_x')\" target=\"_top\"><img src=../Resources/transparent.gif height=3 border=0><br><img src=../Resources/mime_folder.png border=0 align=left>&nbsp;<font face='Lucida Grande, Tahoma' size=2>Reason</a></td></tr></table>";


// ----
// ----
// MOONLIGHT INDEX ENDS.
// ----
// ----


// s[NUM] = "TITLE^URL^CONTENT^OPEN^RANK";